### ISSUE TITLE
US#9-Create Teacher log-in

### ISSUE THREAD

**Issue by ire-mar** [theraf01/Tech-Army#11]
As a teacher, I want to have a log-in page, so that I can view the student details for the activities.

**Comment by Prathyushatirunahari** [comment]
•	The teacher should be able to select the teacher login from the drop down menu.
•	The teacher should not be able to select the admin login from the drop down menu.
•	The teacher should not be able to select the parent login from the drop down menu.
•	The teacher should be able to enter the user name.
•	The teacher should be able to enter the password.
•	The teacher should be able to login by clicking the login button.
•	The teacher should be able to click on the forgot password link.
•	The teacher should be able to go to teacher’s page by clicking valid username and password.
•	The teacher should not be able go to teacher’s page by clicking in-valid username and password.
•	The teacher should not be able go to teacher’s page by clicking valid username and invalid password.
•	The teacher should not be able go to teacher’s page by clicking in-valid username and valid password.
•	The teacher should be able to view the student details by logging in to his/her page.
•	The teacher should not be able to view other details by logging in to his/her page
[document 9.docx](https://github.com/theraf01/Tech-Army/files/4580455/document.9.docx)

**Comment by ire-mar** [comment]
- [x] Text input username and password
- [x] Login Button
