### ISSUE TITLE
US#12-View Child activity details

### ISSUE THREAD

**Issue by ire-mar** [theraf01/Tech-Army#14]
### As a parent, I want to view my child activity detail on my profile page, so I can know when the activity is been scheduled.

[US12 Parent and child wireframe.pdf](https://github.com/theraf01/Tech-Army/files/4705674/US12.Parent.and.child.wireframe.pdf)

**Comment by ire-mar** [comment]
**Acceptance criteria** 
1) The parent should be able to view the details of all of his registered children.
2) The parent should not be able to view the details of other parents’ children.
3) The parent should be able to view the activity details of each child separately by clicking on the respective child name.
4) The parent should not be able to view the activity details of another child of his by clicking on a child name.
5) The parent should be able to view the schedule of activity for which the child has registered.
6) The parent should not be able to view the schedule of activity for which the child has not registered.

**Comment by ire-mar** [comment]
- [x] Open the parent's profile
- [x] View registered activity details of the parent. 
- [x] View  his registered children’s registered activity.
- [x] View the details of the specific child by clicking on the name of child.
- [x] Viewing the map for the specific activity.
- [x] Add any new child for any available activity

**Comment by theraf01** [comment]
Test Case | Command | Target | Value | Result
-- | -- | -- | -- | --
  |   |   |   |  
TC01 | open | http://107.180.46.198/plesk-site-preview/siewebapp.co.nz/parent/login/login.php |   |  
Parent User is authenticated correctly to parent page | type | name=user | THEVIN |  
  | type | name=password | thevin |  
  | click | css=.sign-in-htm .button |   |  
  | Check | linkText=THEVIN | THEVIN |  
  | close | http://107.180.46.198/plesk-site-preview/siewebapp.co.nz/parent/index.php |   | Successful
  |   |   |   |  
TC02 | open | http://107.180.46.198/plesk-site-preview/siewebapp.co.nz/parent/login/login.php |   |  
Parent User is authenticated correctly | type | name=user | THEVIN |  
  | type | name=password | thevin |  
  | click | css=.sign-in-htm .button |   |  
  | Check | linkText=THEVIN | MARIA |  
  | close | http://107.180.46.198/plesk-site-preview/siewebapp.co.nz/parent/index.php |   | Failed
