### ISSUE TITLE
US#13-View estimated driving time

### ISSUE THREAD

**Issue by ire-mar** [theraf01/Tech-Army#15]

**Comment by Prathyushatirunahari** [comment]
Acceptance criteria
•	The parent should able to receive exact location of the summer camp
•	The parent should receive the email from current recipient 
•	The Parent should be able to see map link in the email so the user will be able to browse to the exact location 
[Document 10.docx](https://github.com/theraf01/Tech-Army/files/4704998/Document.10.docx)
 
Task break down

- [x] 	Create a I frame of google calendar in teacher page
- [x] 	Add location of the event in create task of google calendar
- [x] 	Add guest with valid email id and click send.
