### ISSUE TITLE
US#1- Create admin Log-in for Web application

### ISSUE THREAD

**Issue by theraf01** [theraf01/Tech-Army#3]
As an admin, i want a log-in page, so that i can  update the web pages.

**Comment by theraf01** [comment]
Acceptance Criteria: for US#2 -2.As an admin, I want to add activities, so I can create a list of activities in the webpage
	To check whether the user is able view the activities tab in the landing page.
	To check Whether the user is able to click on the activities tab in the landing page
	To check whether the user is able to navigate to the activities page by clicking on the activities tab.
	To check whether the user is able to view the activity images in the activity page
	To check whether the user is able to view the details of the activity page

[US1-Wireframe and AC.docx](https://github.com/theraf01/Tech-Army/files/4580416/US1-Wireframe.and.AC.docx)
x)

**Comment by theraf01** [comment]
Acceptance Criteria: for US#1 - As an admin, I want to have a log-in page, so that I can manage the webpage.
	The admin should be able to enter the user name
	The admin should be able to enter the password
	The admin should be able to login by clicking the login button 
	The admin should be able to click on the forgot password link
	The admin should be able to go to admin page by clicking valid username and password.
	The admin should not be able go to admin page by clicking in-valid username and password.
	The admin should not be able go to admin page by clicking valid username and invalid password.
	 The admin should not be able go to admin page by clicking in-valid username and valid password.
[US1-Wireframe and AC.docx](https://github.com/theraf01/Tech-Army/files/4580456/US1-Wireframe.and.AC.docx)

**Comment by ire-mar** [comment]
[]create database table

**Comment by ire-mar** [comment]
- [ ] Create database Table

**Comment by ire-mar** [comment]
- [ ] Create a database Table
- [ ] Login Button

**Comment by ire-mar** [comment]
-[ ]Text input box for username and password
 -[ ] Create a database table 
  -[ ] Login Button

**Comment by ire-mar** [comment]
- [x] Text input for username and password

**Comment by ire-mar** [comment]
- [x] Create a database table
- [x] Login Button

**Comment by theraf01** [comment]
- [x]  Testing using Selenium completed


Test Case | Command | Target | Value | Result
-- | -- | -- | -- | --
  |   |   |   |  
TC01   Services page  authenticated correctly | open | https://siewebapplication.000webhostapp.com/SMS/login.php |   |  
click | linkText=Services |   |  
assert title | Services |   |  
close | https://siewebapplication.000webhostapp.com/services.php |   |  |Successful
  |   |   |   |  
TC02   Services page  authenticated incorrectly | open | https://siewebapplication.000webhostapp.com/SMS/login.php |   |  
click | linkText=Services |   |  
assert title | About us |   |  
close | https://siewebapplication.000webhostapp.com/services.php |   |  |Failed
  |   |   |   |
