### ISSUE TITLE
US#2-Create a list of activities

### ISSUE THREAD

**Issue by ire-mar** [theraf01/Tech-Army#4]
As an admin, I want to add activities, so that I can create a list of activities in the web application.

**Comment by theraf01** [comment]
[US2-Wireframe and AC.docx](https://github.com/theraf01/Tech-Army/files/4580425/US2-Wireframe.and.AC.docx)

Acceptance Criteria: for US#2 -2.As an admin, I want to add activities, so I can create a list of activities in the webpage
	To check whether the user is able view the activities tab in the landing page.
	To check Whether the user is able to click on the activities tab in the landing page
	To check whether the user is able to navigate to the activities page by clicking on the activities tab.
	To check whether the user is able to view the activity images in the activity page
	To check whether the user is able to view the details of the activity page

**Comment by ire-mar** [comment]
- [x] List the activities
- [ ] Register Button

**Comment by theraf01** [comment]
- [x] Testing using Selenium IDE 

Test Case | Command | Target | Value | Result
-- | -- | -- | -- | --
  |   |   |   |  
TC01   Admin User is authenticated correctly | open | https://siewebapplication.000webhostapp.com/SMS/login.php |   |  
type | name=user | admin |  
type | name=password | admin |  
click | name=login |   |  
assert title | SMS |   |  
close | https://siewebapplication.000webhostapp.com/SMS/index.php |   | Successful
  |   |   |   |  
TC02   Admin page password is blank | open | https://siewebapplication.000webhostapp.com/SMS/login.php |   |  
type | name=user | admin |  
type | name=password |   |  
click | name=login |   |  
answer on next prompt | Warning implicit locators are deprecated, please change the   locator to id=Please fill out this field |   |  
close | https://siewebapplication.000webhostapp.com/SMS/login.php |   |  
  |   |   |   | Successful

**Comment by theraf01** [comment]
Task completed
