### ISSUE TITLE
US#4-Access Student registration to edit student details

### ISSUE THREAD

**Issue by ire-mar** [theraf01/Tech-Army#6]
As an admin, I want to access student registration details, so that I can add student details.

**Comment by theraf01** [comment]
**Acceptance Criteria US#4** - As an admin, I want to access registration details, so I can edit or update student details. 
	As an admin, I want to access registration details, so I can edit or update student details.
	The admin should be able to click on the edit student detail button
	The admin should be able to click on the update student detail button
	The user should be able browse to edit page
	The user should be able browse to update page
	The admin should be able to edit student details
	The admin should be able to update

[US4-Wireframe and AC.docx](https://github.com/theraf01/Tech-Army/files/4580506/US4-Wireframe.and.AC.docx)

**Comment by theraf01** [comment]
- [x] Log In Button
- [x] Insert Student detail Button
- [x] Submit Student details  
- [x] Display Student Info
